adding productId as a property
BKWLD/shopify-gtm-instrumentor pull request #15
Opened 2021-05-26 20:09 UTC by mattaebersold

@weotch I was having trouble seeing this locally when linked (slack) but it's such a simple change I created the request anyways

2021-05-26 20:47 UTC, mattaebersold commented
ok @weotch it works as expected: 
![image](https://user-images.githubusercontent.com/435606/119728991-f860e100-be28-11eb-8400-d21983375604.png)

2021-05-26 23:55 UTC, weotch requested changes
Can you recompile and push up after making these changes?

2021-05-26 23:55 UTC, weotch commented on index.coffee
> +	console.log 'id', id
Remove console logs

```suggestion
```

2021-05-26 23:55 UTC, weotch commented on index.coffee
> +	console.log 'id', id
```suggestion
```

2021-05-27 00:22 UTC, mattaebersold commented
@weotch shoot, yea sorry it's updated

2021-05-27 00:47 UTC, weotch approved these changes

2021-05-27 00:47 UTC, merged

2021-05-27 01:22 UTC, weotch commented
@mattaebersold this is tagged as `0.3.0` now.  Thanks for the add!